export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const MEDICINE_GET = "MEDICINE_GET"
export const MEDICINE_ADD = "MEDICINE_ADD"
export const MEDICINES_UPDATE = "MEDICINES_UPDATE"
export const MEDICINES_DELETE = "MEDICINES_DELETE"