export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const MEDICINES_GET = "MEDICINES_GET"
export const MEDICINES_ADD = "MEDICINES_ADD"
export const MEDICINES_UPDATE = "MEDICINES_UPDATE"
export const MEDICINES_DELETE = "MEDICINES_DELETE"